# permissions for end users to edit grafanateams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: grafanaoperator
    app.kubernetes.io/managed-by: kustomize
  name: grafanateam-editor-role
rules:
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanateams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanateams/status
  verbs:
  - get
