# permissions for end users to view grafanaorganizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: grafanaoperator
    app.kubernetes.io/managed-by: kustomize
  name: grafanaorganization-viewer-role
rules:
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanaorganizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanaorganizations/status
  verbs:
  - get
