---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanaorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanaorganizations/finalizers
  verbs:
  - update
- apiGroups:
  - grafana.tcodelab.com
  resources:
  - grafanaorganizations/status
  verbs:
  - get
  - patch
  - update
