apiVersion: grafana.tcodelab.com/v1alpha1
kind: GrafanaOrganization
metadata:
  labels:
    app.kubernetes.io/name: grafanaoperator
    app.kubernetes.io/managed-by: kustomize
  name: grafanaorganization-sample
spec:
  # TODO(user): Add fields here
